// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7SayWSqhBcA7x5vcsRY-o8mDxTO2hodc',
    appId: '1:803423453979:web:b10122d8c3fd40fea549be',
    messagingSenderId: '803423453979',
    projectId: 'flutter-slutprojekt',
    authDomain: 'flutter-slutprojekt.firebaseapp.com',
    storageBucket: 'flutter-slutprojekt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJfHzC-vhJyfS4-OJlBW3H7LguCIlSMAs',
    appId: '1:803423453979:android:4c7f609d76159406a549be',
    messagingSenderId: '803423453979',
    projectId: 'flutter-slutprojekt',
    storageBucket: 'flutter-slutprojekt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDfwowUqMzwGHjfaoN8vHDhOalBJUYbgQ',
    appId: '1:803423453979:ios:54984708a7d078cba549be',
    messagingSenderId: '803423453979',
    projectId: 'flutter-slutprojekt',
    storageBucket: 'flutter-slutprojekt.appspot.com',
    iosBundleId: 'com.example.flutterSlutprojekt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDfwowUqMzwGHjfaoN8vHDhOalBJUYbgQ',
    appId: '1:803423453979:ios:3620488ead9aa280a549be',
    messagingSenderId: '803423453979',
    projectId: 'flutter-slutprojekt',
    storageBucket: 'flutter-slutprojekt.appspot.com',
    iosBundleId: 'com.example.flutterSlutprojekt.RunnerTests',
  );
}
